dataset:
  data_folder_path: /home/matin/school/Amir_Omidvarnia/prepared_data
  idx2names_path: /home/matin/school/Amir_Omidvarnia/data_idx2name_train.pkl
  loader_name: HCPData
  name: PicVocab_Unadj
  target_transform: ToTensor
  train_ratio: 0.8
  transform: HCPTransform
device: gpu
exp_dir: exp/Liangwei/PicVocab_Unadj
exp_name: Liangwei
gpus:
- 0
model:
  cnn_in_channels: 64620
  cnn_out_channels: 32
  max_pool_size: 5
  name: Liangwei
  rnn_hidden_size: 32
  window_size: 96
runner: LiangweiRunner
seed: 1234
test:
  batch_size: 1
  num_workers: 0
  test_model_dir: null
  test_model_name: model_snapshot_PicVocab_Unadj.pth
train:
  batch_size: 10
  criterion: regression_loss
  display_iter: 5
  is_resume: false
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 100000000
  max_epoch: 100
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_dir: null
  resume_epoch: 5000
  resume_model: null
  snapshot_epoch: 1
  wd: 0.0
use_gpu: true
